### ISSUE TITLE
How to make compile.hxml file ?

### ISSUE THREAD

**Issue by nvcken** [nanjizal/canvasImageTriangle#2]
I'm new with Haxe, would you please tell how to make and run compile.hxml file ?

**Comment by nanjizal** [comment]
Hi nvcken,
1) first you need to install a version of Haxe current one should work, but you could also try preview4 if your feeling adventurous.
https://haxe.org/download/list/
2) you need to setup haxelib normally before starting from terminal.
https://lib.haxe.org/documentation/using-haxelib/#setup
3) The dependancy **htmlHelper** is needed. It's not in haxelib only on github so you need to install it so from terminal.
https://lib.haxe.org/documentation/using-haxelib/#git
so you need something like
`haxelib git htmlHelper https://github.com/nanjizal/htmlHelper.git`
4) from terminal you can run
`haxe complie.hxml`
but the file is setup for mac use so you may need to change the last line of compile.hxml which just runs the mac open command, you can hash/comment it out and do in manually.
`#-cmd open bin/index.html`
If you get stuck then there are gitter channels for Haxe, there is Kha IRC which is often really helpful etc.. or you can post back here and will try to help you further, there is a lot of info on the haxe.org site the cookbook section is worth exploring as it's maybe a bit more hands on than the rest of the site.
